ALTER TABLE cities
    ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE NULL;

ALTER TABLE cities
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

UPDATE cities
SET created_at = CURRENT_TIMESTAMP
WHERE created_at IS NULL;

ALTER TABLE cities
    ALTER COLUMN created_at SET NOT NULL;
