spring.application.name=demo-rest

logging.level.org.springframework.web=DEBUG
#logging.level.edu.rutmiit.demo=DEBUG
# DB
spring.datasource.url=jdbc:postgresql://localhost:5433/ways
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Naming strategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false
# sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true